### ISSUE TITLE
Add support for Chinese

### ISSUE THREAD

**Issue by xCaoCao** [landonepps/MorphMan21#10]
There was a [Chinese version](https://github.com/NinKenDo64/Jieba-Morph) of morphman for Anki 2.0 but it seems abandoned. 
So could you add support for Chinese?

**Comment by shanrauf** [comment]
I'll look into this!

**Comment by xCaoCao** [comment]
Thank you!

**Comment by shanrauf** [comment]
@xCaoCao Since I study Japanese and not Chinese, I have never used this before, but do you know what the difference is between the CJK character morphemizer and the Jieba morphemizer that you'd like? Because the CJK morphemizer is already included in this version of Morphman, but I've never actually tried using it

**Comment by xCaoCao** [comment]
@shanrauf I think you're right and zhon only does things at the character level. Word level stuff seems to be restricted to Pinyin which is not very helpful.

**Comment by xCaoCao** [comment]
If you need any help, I can (more or less) program. But I never made an Anki addon before execept the 2.1 version of "No Penalties or Boosting", which was easy and hacked together, nor used much Python xD

**Comment by shanrauf** [comment]
No worries, I just finished adding Chinese support and created a pull request. In the meantime, you can download it directly from my (repository)[https://github.com/shanrauf/MorphMan21/tree/add-chinese-support]!

**Comment by xCaoCao** [comment]
Wow that was fast

**Comment by xCaoCao** [comment]
@shanrauf mhh 
``
 File "C:\Users\Stephen\AppData\Roaming\Anki2\addons21\MorphMan21\morph\deps\jieba\posseg\__init__.py", line 5, in <module>
    import jieba
<class 'ModuleNotFoundError'>: No module named 'jieba'

**Comment by shanrauf** [comment]
@xCaoCao Lol sorry about that I know what the problem is and should have tested it way more thoroughly before commiting it... give me a minute.

**Comment by shanrauf** [comment]
@xCaoCao It works well for me now. On Anki, press File and Export your collection to create a backup of your cards before testing it out [here](https://github.com/shanrauf/MorphMan21/tree/add-chinese-support). You don't need to backup but better safe than sorry.

**Comment by xCaoCao** [comment]
Seems to work. Thanks!
