### ISSUE TITLE
Parenthesized note name's MorphMan_* fields empty

### ISSUE THREAD

**Issue by khonkhortisan** [landonepps/MorphMan21#16]
Hindi Vocab 2017 https://ankiweb.net/shared/info/613183013 and
2800 Hindi sentences [with audio] + romanisation https://ankiweb.net/shared/info/2077353002 are sorted, but
Hindi-English 50000 https://ankiweb.net/shared/info/257144969 has empty MorphMan_* fields, I'm guessing because it has parentheses in its note name `Basic (and reversed card)-f943c`
![image](https://user-images.githubusercontent.com/1996449/59651082-5664f400-913d-11e9-80d4-fb0cf9a59d91.png)

**Comment by shanrauf** [comment]
Hello @khonkhortisan. I just tested the deck you stated was causing the issue, and it seems to have worked fine for me even though the note type has parentheses in it (although I did notice that the recalc took a long time). Perhaps you forgot to add the MorphMan_Focus field to your cards? If you think there is still an issue then please try to further describe the issue you're having.
