### ISSUE TITLE
Give higher priority to words depending on where they are in priority.db

### ISSUE THREAD

**Issue by shanrauf** [landonepps/MorphMan21#23]
Most people use frequency lists as their priority.db, so it would make more sense and be more efficient for learning if words at the top of the frequency list were given more priority than words at the bottom of the frequency list. Currently, all words in a priority.db are given the same priority.

**Comment by landonepps** [comment]
I don't think this enhancement makes sense because it looks like the database is just a serialized python dictionary. Unlike arrays, dictionaries aren't ordered objects. There's no guarantee that the database will keep the same order.

**Comment by shanrauf** [comment]
Ah I see, yeah it probably wouldn't be possible using the priority db. There'd need to be a separate feature that takes a raw frequency list to even make the feature possible.

**Comment by landonepps** [comment]
Yeah, you'd have to set up something like that. It's a good idea, but it won't work with the current setup.
