### ISSUE TITLE
morphHighlight not working when word is capitalized

### ISSUE THREAD

**Issue by chickendude** [landonepps/MorphMan21#40]
All morphs are turned into lowercase, so the regexp in nonSpanSub:

https://github.com/landonepps/MorphMan21/blob/b8ae58b74feacfa0d86b304b849a6f57f51f91ca/morph/newMorphHelper.py#L206

...misses it, preventing it from receiving the appropriate highlighting class. Obviously this isn't an issue for CJK languages, but it is for languages that differentiate between upper/lowercase.

Setting the "re.IGNORECASE" flag (`re.sub( sub, repl, s, flags=re.IGNORECASE)`) gets around it, but it has the side effect of turning the word into lowercase. I can't think of a non-trivial way to get around this (e.g. what if the word is used multiple times? "**To** be or not **to** be.")

**Comment by ianki** [comment]
This should fix it https://github.com/landonepps/MorphMan21/pull/43

**Comment by shanrauf** [comment]
Fixed by #43

**Comment by chickendude** [comment]
Yep, that's fixed it for me, thanks!
