### ISSUE TITLE
AnkiWeb package contains __MACOSX and .DS_Store files

### ISSUE THREAD

**Issue by Kebigon** [landonepps/MorphMan21#52]
Hi Landon,

Thank you for your great work on this add-on.

I'm opening this issue because I noticed that the package present in AnkiWeb contains Mac OS X specific files, and I think those are not required for the add-on to work properly. As those are not present in the git repository, I think they have been included during the release process.

* 900801631/morph/browser/.DS_Store
* 900801631/__MACOSX/
* 900801631/__MACOSX/morph/
* 900801631/__MACOSX/morph/browser/
* 900801631/__MACOSX/morph/browser/._.DS_Store

Would it be possible to remove them ?

Sincerely,
Kebigon

**Comment by landonepps** [comment]
That one's on me. The files are generated by macOS's standard zip utility and are hidden for Mac users, so I didn't notice. It should be fixed now.
