### ISSUE TITLE
Skipping cards doesn't work when using v2 scheduler.

### ISSUE THREAD

**Issue by Geniusssmit** [landonepps/MorphMan21#6]
Anki 2.1 https://i.imgur.com/2K6D46d.png 3 first options is not working.

I used 2.0 with morphman before, it used to "lag" for few seconds after recalc function and skip all cards with due<10000 when i go to my decks, now it just show me every card in due order.

What should I do? Maybe something wrong in config file?

**Comment by Geniusssmit** [comment]
Wow, turns out without experimental V2 scheduler everything is fine.
This is disappointing..

**Comment by shanrauf** [comment]
Woah I think you are correct! Turned off my V2 scheduler and it seems like things have changed. Hopefully @landonepps or someone else can figure out how to add V2 compatiblity, because I have no idea how to do that...

**Comment by landonepps** [comment]
Nice find! I don't have time to work on it at the moment, but I can look into it when I get some free time.
If there's anyone else that wants to work on it, be my guest.
