### ISSUE TITLE
Error when recalculating in Anki 2.1.35

### ISSUE THREAD

**Issue by PeanutChin77** [landonepps/MorphMan21#62]
![image](https://user-images.githubusercontent.com/75569086/101279718-1c8b2000-37ff-11eb-979e-2034c6dbd992.png)

**Comment by landonepps** [comment]
I think I fixed it. Try updating MorphMan and running it again.

**Comment by PeanutChin77** [comment]
> I think I fixed it. Try updating MorphMan and running it again.
 
Can confirm the fix is working!
